title: 教主
description: "Hi，我是教主，是一个运维工程师，会一点 Java / Golang / React.js，喜欢折腾各种新技术。"

github: jiaozhu
zhihu: errstack
twitter: jiaozhu
v2ex: jiaozhu

url: https://jiaozhu.net
menu:
  - title: "Categories"
    url: "/categories.html"
  - title: "Github"
    url: "https://github.com/jiaozhu"
  - title: "RSS"
    url: "/feed.xml"

timezone: Asia/Shanghai
locale: zh_CN
lang: zh-cmn-Hans
future: true
highlighter: rouge
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

permalink: /:year-:month-:day/:title.html
assetUrl: //jiaozhu.org/images/
defaultImage: data:image/gif;base64,R0lGODlhAQABAAAAACH5BAEKAAEALAAAAAABAAEAAAICTAEAOw==

google_analytics:
baidu_verify:
google_verify:

paginate: 10
post_ext: md
page_ext: md
post_layout: post
page_layout: page
titlecase: true

showBuyCoffee: false
payImage:

include: [".htaccess"]
exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "README.md",
    "LICENSE",
    "package.json",
    "node_modules",
  ]

plugins:
  - jekyll-pdf-embed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
